### ISSUE TITLE
Exception in `MediaDevice.VendorOpcodes` - 'ToInt does not work for value type VT_UI4'

### ISSUE THREAD

**Issue by finlaybob** [Bassman2/MediaDevices#110]
**Describe the bug**
Method throws `InvalidOperationException` on returning.

```
System.InvalidOperationException: ToInt does not work for value type VT_UI4
   at MediaDevices.Internal.PropVariantFacade.ToInt()
   at MediaDevices.MediaDevice.<>c.<VendorOpcodes>b__150_0(PropVariantFacade p)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
```

**To Reproduce**
1. Connect a device
2. Run the following code.
```cs
var device = MediaDevice.GetDevices().First();
var device.Connect();
var opcodes = device.VendorOpcodes().ToArray();
```
**Expected behavior**
An IEnumerable of ints is returned. 

**Device**
Samsung A33 5G, Android 13
Apple iPhone 6, iOS 12.5.7

**Version:**
Nuget Package 1.10.0

**Additional context**

**Comment by Bassman2** [comment]
Fixed in version 2.x

**Comment by finlaybob** [comment]
Nice, that was an old one :) 
Thanks!

**Comment by Bassman2** [comment]
Preview 1 available at https://www.nuget.org/packages/MediaDevices/2.0.0-preview.1.1000
