### ISSUE TITLE
DownloadFile NotImplementedException

### ISSUE THREAD

**Issue by enantiomer2000** [Bassman2/MediaDevices#22]
I was testing out the MediaDevice.DownloadFile method as it was used in your Unit Test:

                    using (MemoryStream stream = new MemoryStream())
                    {
                        device.DownloadFile(filePath, stream);
                        position = stream.Length;

                        using (FileStream file = File.Create(localPath))
                        {
                            stream.Position = 0;
                            stream.CopyTo(file);
                        }
                    }

And I keep getting a NotImplementedException:
at System.Runtime.InteropServices.ComTypes.IStream.Stat(STATSTG& pstatstg, Int32 grfStatFlag)
   at MediaDevices.StreamWrapper.get_Length()
   at System.IO.Stream.GetCopyBufferSize()
   at MediaDevices.MediaDevice.DownloadFile(String path, Stream stream)
   at TestAndroidFileTransfer.Program.Main(String[] args) in C:\Users\Jonathan\source\testrepos\TestAndroidFileTransfer\TestAndroidFileTransfer\Program.cs:line 26

Have you seen this issue before? It is not immediately apparent what is going on..

**Comment by enantiomer2000** [comment]
Never mind. It looks like my project was referencing .Net Core 2.1 where the method was not implemented yet. It works in .Net Framework 4.6 and I will assume .Net Core 3.0.

**Comment by Bip901** [comment]
I get the very same exception on .NET 5 - any workarounds/fixes?
